In [1]:
!nvidia-smi

Fri Feb 19 10:01:02 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8    11W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
from __future__ import print_function
import torch

In [3]:
#empty gives unknown uniniliazed matrix,whatever values were allocated in the memory will appear as intial values
#Here 5 and 4 represents number of rows and columns in the matrix
#whatever values appeared first,so it doesnt work like rand
a=torch.empty(5,4)
print(a)

tensor([[5.9333e-36, 0.0000e+00, 7.0065e-44, 6.8664e-44],
        [6.3058e-44, 6.7262e-44, 7.0065e-44, 6.3058e-44],
        [6.8664e-44, 7.9874e-44, 1.1771e-43, 6.8664e-44],
        [6.7262e-44, 8.1275e-44, 6.7262e-44, 6.8664e-44],
        [8.1275e-44, 6.8664e-44, 7.1466e-44, 6.4460e-44]])


In [4]:
b=torch.rand(5,4)
print(b)

tensor([[0.6651, 0.7171, 0.3126, 0.4585],
        [0.5928, 0.4963, 0.7056, 0.4516],
        [0.7913, 0.0817, 0.3687, 0.4202],
        [0.5351, 0.1999, 0.9278, 0.7861],
        [0.3347, 0.0904, 0.6569, 0.7698]])


In [5]:
c=torch.tensor([5,4])
print(c)

tensor([5, 4])


In [6]:
c=c.new_ones(5,4,dtype=torch.float)
print(c)
c=torch.randn_like(c,dtype=torch.float)
print(c)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[-0.3030, -0.3784,  0.1187,  0.1845],
        [-0.6022, -0.8687,  0.3719,  2.4439],
        [ 0.4232, -2.4273, -0.9538,  0.2081],
        [ 0.2393,  1.0095,  0.7916,  2.5159],
        [-1.8034,  1.0484,  1.0860, -0.6205]])


In [7]:
d=torch.randn(5,4)
print(torch.add(c,d))

tensor([[-1.7180, -0.9906,  1.4800, -0.0705],
        [-1.2225,  0.2817, -0.2577,  2.1691],
        [ 1.1459, -1.9169, -0.1455,  0.9591],
        [-0.6983,  0.8649, -1.0183,  2.1650],
        [-2.0617,  1.6943,  1.2081, -1.1174]])


In [8]:
b=torch.empty(5,4)
c=torch.empty(5,4)
print(b)
print(c)

tensor([[5.9334e-36, 0.0000e+00, 7.0065e-44, 6.8664e-44],
        [6.3058e-44, 6.7262e-44, 7.0065e-44, 6.3058e-44],
        [6.8664e-44, 7.9874e-44, 1.1771e-43, 6.8664e-44],
        [6.7262e-44, 8.1275e-44, 6.7262e-44, 6.8664e-44],
        [8.1275e-44, 7.0065e-44, 7.8473e-44, 6.4460e-44]])
tensor([[5.9334e-36, 0.0000e+00, 3.1264e-01, 4.5847e-01],
        [5.9281e-01, 4.9635e-01, 7.0560e-01, 4.5160e-01],
        [7.9126e-01, 8.1732e-02, 3.6869e-01, 4.2016e-01],
        [5.3514e-01, 1.9986e-01, 9.2780e-01, 7.8614e-01],
        [3.3470e-01, 9.0412e-02, 6.5695e-01, 7.6985e-01]])


In [9]:
print(b.add(c))

tensor([[1.1867e-35, 0.0000e+00, 3.1264e-01, 4.5847e-01],
        [5.9281e-01, 4.9635e-01, 7.0560e-01, 4.5160e-01],
        [7.9126e-01, 8.1732e-02, 3.6869e-01, 4.2016e-01],
        [5.3514e-01, 1.9986e-01, 9.2780e-01, 7.8614e-01],
        [3.3470e-01, 9.0412e-02, 6.5695e-01, 7.6985e-01]])


In [10]:
if torch.cuda.is_available():
  device=torch.device("cuda") #a cuda object
  y=torch.ones_like(c,device=device)  #directly create a tensor on gpu
  c=c.to(device)    #move the tensor to gpu
  z=y+c
  print(z)

tensor([[1.0000, 1.0000, 1.3126, 1.4585],
        [1.5928, 1.4963, 1.7056, 1.4516],
        [1.7913, 1.0817, 1.3687, 1.4202],
        [1.5351, 1.1999, 1.9278, 1.7861],
        [1.3347, 1.0904, 1.6569, 1.7698]], device='cuda:0')


In [11]:
device

device(type='cuda')

# Alexnet neural network

In [12]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchsummary import summary
out_classes = 10

def conv_block(in_channels, out_channels,kernel=3,s=1,p=1, pool=False):
    layers = [nn.Conv2d(in_channels, out_channels, kernel_size=kernel,stride=s,padding=p), 
              nn.BatchNorm2d(out_channels), 
              nn.ReLU(inplace=True)]
    if pool: layers.append(nn.MaxPool2d(2))
    return nn.Sequential(*layers)

class neural_network(nn.Module):

  def __init__(self):
    super(neural_network,self).__init__()
    #3,224,224
    self.conv1 = conv_block(3, 96,kernel=11,s=4,p=1,pool=True) #96,54,54 --> #96,27,27
    self.conv2 = conv_block(96, 256,kernel=5,s=1,p=2,pool=True) #256,27,27 --> #256,13,13
    self.conv3= conv_block(256,384,kernel=3,s=1,p=1)#384,13,13
    self.conv4= conv_block(384,384,kernel=3,s=1,p=1)#384,13,13
    self.conv5= conv_block(384, 256,kernel=3,s=1,p=1,pool=True)#256,6,6
    self.flatten = nn.Flatten()#256*6*6
    self.drop = nn.Dropout(0.5)
    self.fc1=nn.Linear(256*6*6,4096)
    self.fc2=nn.Linear(4096,1000)
    self.fc3=nn.Linear(1000,out_classes)
    self.soft=nn.Softmax(dim=1)

  def forward(self,x):
    out = self.conv1(x)
    out = self.conv2(out)
    out = self.conv3(out)
    out = self.conv4(out)
    out = self.conv5(out)
    out = self.flatten(out)
    out = self.drop(out)
    out = self.fc1(out)
    out = self.fc2(out)
    out = self.fc3(out)
    out = self.soft(out)
    
    return out

x = torch.randn(1,1,32,32)
model=neural_network()
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

x=torch.FloatTensor(x).to(device)
model=model.to(device)
summary(model,(3,227,227))


----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1           [-1, 96, 54, 54]          34,944
       BatchNorm2d-2           [-1, 96, 54, 54]             192
              ReLU-3           [-1, 96, 54, 54]               0
         MaxPool2d-4           [-1, 96, 27, 27]               0
            Conv2d-5          [-1, 256, 27, 27]         614,656
       BatchNorm2d-6          [-1, 256, 27, 27]             512
              ReLU-7          [-1, 256, 27, 27]               0
         MaxPool2d-8          [-1, 256, 13, 13]               0
            Conv2d-9          [-1, 384, 13, 13]         885,120
      BatchNorm2d-10          [-1, 384, 13, 13]             768
             ReLU-11          [-1, 384, 13, 13]               0
           Conv2d-12          [-1, 384, 13, 13]       1,327,488
      BatchNorm2d-13          [-1, 384, 13, 13]             768
             ReLU-14          [-1, 384,